"""add fields to book model

Revision ID: 20260126195748
Revises: 20251222211731
Create Date: 2026-01-26 19:57:49.820302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.books.models import BookStatus

# revision identifiers, used by Alembic.
revision: str = '20260126195748'
down_revision: Union[str, Sequence[str], None] = '20251222211731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('cover_url', sa.String(length=512), nullable=True))
    book_status_enum = sa.Enum(
        BookStatus,
        name="book_status",
    )

    book_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "books",
        sa.Column(
            "status",
            book_status_enum,
            nullable=False,
            server_default=BookStatus.draft.value,
        ),
    )
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_column('books', 'status')
    op.drop_column('books', 'cover_url')
    op.drop_column('books', 'rating')
    op.drop_column('books', 'pages')
    op.drop_column('books', 'language')
    op.drop_column('books', 'published_year')
    op.drop_column('books', 'description')
    op.drop_column('books', 'isbn')

    op.execute("DROP TYPE IF EXISTS book_status")
    # ### end Alembic commands ###
