"""add new fields to writer

Revision ID: 20260127135941
Revises: 20260127125823
Create Date: 2026-01-27 13:59:42.259158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260127135941'
down_revision: Union[str, Sequence[str], None] = '20260127125823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('uq_genres_slug'), 'genres', type_='unique')
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.add_column('writers', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('writers', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('writers', sa.Column('death_date', sa.Date(), nullable=True))
    op.add_column('writers', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writers', 'country')
    op.drop_column('writers', 'death_date')
    op.drop_column('writers', 'birth_date')
    op.drop_column('writers', 'bio')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    # op.create_unique_constraint(op.f('uq_genres_slug'), 'genres', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
